from enum import Enum


class Actions:
    
    CANCEL_RESERVATION = "CANCEL_RESERVATION",

    EDIT_PERSON = "EDIT_PERSON"
    DELETE_PERSON = "DELETE_PERSON"

    CREATE_RESERVATION = "CREATE_RESERVATION"
    DELETE_RESERVATION = "DELETE_RESERVATION"